"""create artists table

Revision ID: 51ed1a5c865e
Revises: 
Create Date: 2025-07-02 22:07:12.245844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ed1a5c865e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dna_visibility', sa.Enum('public', 'private', 'draft', name='visibility_enum'), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('license_type', sa.String(), nullable=True),
    sa.Column('tracks_visibility', sa.Enum('visible', 'invisible', name='tracks_enum'), nullable=True),
    sa.Column('become_partner', sa.Boolean(), nullable=True),
    sa.Column('audio_preview_url', sa.String(), nullable=True),
    sa.Column('sensitivity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'complete', name='status_enum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    # ### end Alembic commands ###
